In [1]:
 import numpy as np

In [2]:
vector = np.array([2,4,2])
vector

array([2, 4, 2])

In [3]:
matrix = np.array([[2,4,2], [5,6,2]])
matrix

array([[2, 4, 2],
       [5, 6, 2]])

In [4]:
np.mean(matrix)

3.5

In [5]:
np.mean(matrix, axis = 0)

array([3.5, 5. , 2. ])

In [6]:
np.mean(matrix, axis = 1)

array([2.66666667, 4.33333333])